using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using TMPro;

// –ï—Å—Ç—å –±–∞–≥–∏: –∏–≥—Ä–æ–∫ –º–æ–∂–µ—Ç—å –Ω–∞–∂–∏–º–∞—Ç—å –Ω–∞ –∞—Ç–∞–∫—É / –∏–≥—Ä–∞—Ç—å –∫–∞—Ä—Ç—ã –∫–æ–≥–¥–∞ —É–≥–æ–¥–Ω–æ.
// –ù—É–∂–Ω–æ –æ–≥—Ä–∞–Ω–∏—á–∏—Ç—å –∏–≥—Ä–æ–∫–∞ ‚ùåüóΩ
//
// –ü–æ —Ö–æ—Ä–æ—à–µ–º—É –º—ã —Å–ø–∞–≤–Ω–∏–º –±–æ–π —á–µ—Ä–µ–∑ Instantiate –∏ –ø—Ä–æ–∫–∏–¥—ã–≤–∞–µ–º
// –≤ –Ω–µ–≥–æ –≤—Å–µ –Ω—É–∂–Ω—ã–µ –ø–æ–ª—è. –≠—Ç–æ —Ç–æ –∫–∞–∫ —è –≤–∏–∂—É üñå
public class Fight : MonoBehaviour {
    // –î–ª—è –ø–æ–∑–∏—Ü–∏–æ–Ω–∏—Ä–æ–≤–∞–Ω–∏—è –æ–±—ä–µ–∫—Ç–æ–≤:
    // FightArea -- parent,
    // PlayerPokemonSpawnPoint -- –ø–æ–∑–∏—Ü–∏—è –≤–Ω—É—Ç—Ä–∏ FightArea
    public GameObject FightArea;
    public Transform PlayerPokemonSpawnPoint;
    public Transform EnemyPokemonSpawnPoint;

    public FightState State;
    public PlayerHandInBattle PlayerHand;
    public EnemyAI Enemy;

    public Pokemon PlayerPokemon;
    public Pokemon EnemyPokemon;
    
    public Button AttackButton;

    [Header("–í–∏–∑—É–∞–ª—å–Ω–∞—è —à–µ–ª—É—Ö–∞")]
    public TextMeshProUGUI EnemyPokemonName;
    public TextMeshProUGUI Bonus1Text;
    public Image EnemyPokemonColor;
    public TextMeshProUGUI PlayerPokemonName;
    public TextMeshProUGUI Bonus2Text;
    public Image PlayerPokemonColor;

    private void Start() {
        Card enemyFirstCard = Enemy.FirstTurn();    
        Pokemon pokemon = Instantiate(enemyFirstCard.Config.Pokemon, FightArea.transform);
        pokemon.Construct(enemyFirstCard);
        pokemon.transform.position = EnemyPokemonSpawnPoint.position;
        EnemyPokemon = pokemon;
        
        State = FightState.WaitingForPlayerToSpawnHisFirstPokemon;
        PlayerHand.Construct(Singleton<FullDeck>.Instance);
    }
    
    private void OnEnable() {
        PlayerHand.CardPlayed += OnPlayerCardPlayed;
    }
    
    private void OnDisable() {
        PlayerHand.CardPlayed -= OnPlayerCardPlayed;
    }
    
    private void Update() {
        // –Ø –ø–∏—à—É –∫–æ–¥ –≤ Notepad++ üòã, —Ç—É—Ç –Ω–µ—Ç –ø–æ–¥—Å–∫–∞–∑–æ–∫. –ê —á—Ç–æ –¥–µ–ª–∞—Ç—å?
        // JetBrains —É—à–ª–∏ –∏–∑ –†–æ—Å—Å–∏–∏ ü§¨. –ê –∫–∞–∫ –≤—ã –¥—É–º–∞–µ—Ç–µ? –¢–∞–∫ –∏ –∂–∏–≤—ë–º. ü§ê
        if (State != FightState.PlayerTurn) {
            AttackButton.interactable = false;
        } else {
            AttackButton.interactable = true;
        }
        
        if ((PlayerPokemon == null || PlayerPokemon.Card.CurrentHealth.IsZero) && PlayerHand.OutOfCards) {
            Debug.Log("–ò–≥—Ä–æ–∫ –ø—Ä–æ–∏–≥—Ä–∞–ª –∞—Ö–∞—Ö–∞—Ö");
            SceneManager.LoadScene("Overworld");
        }
        
        if (EnemyPokemon.Card.CurrentHealth.IsZero) {        
            Debug.Log($"–í—Ä–∞–≥ {Enemy.CharacterID} –ø—Ä–æ–∏–≥—Ä–∞–ª. –ö—Ä—É—Ç–æ?");
            Singleton<NPCState>.Instance.States[Enemy.CharacterID] = CharacterState.Defeated;
            SceneManager.LoadScene("Overworld");
        }
        
        if (EnemyPokemon == null || EnemyPokemon.Card.CurrentHealth.IsZero) {
            EnemyPokemonName.text = "*–º–µ—Ä—Ç–≤*";
            EnemyPokemonColor.color = Color.gray;
        } else {
            EnemyPokemonName.text = EnemyPokemon.Card.Config.Name;
            EnemyPokemonColor.color = EnemyPokemon.Card.Config.Color;
        }
        
        if (PlayerPokemon == null || PlayerPokemon.Card.CurrentHealth.IsZero) {
            PlayerPokemonName.text = "*–∂–¥–µ–º –ø–æ–∫–µ–º–æ–Ω–∞*";
            PlayerPokemonColor.color = Color.gray;
        } else {
            PlayerPokemonName.text = PlayerPokemon.Card.Config.Name;
            PlayerPokemonColor.color = PlayerPokemon.Card.Config.Color;
        }
        
        double bonus1 = 0.0;
        double bonus2 = 0.0;
        if (!(PlayerPokemon == null || PlayerPokemon.Card.CurrentHealth.IsZero) &&
            !(EnemyPokemon == null || EnemyPokemon.Card.CurrentHealth.IsZero))
        {
            bonus1 = ColorInfo.DamageBonuses[EnemyPokemon.Card.Config.ColorType][PlayerPokemon.Card.Config.ColorType];
            bonus2 = ColorInfo.DamageBonuses[PlayerPokemon.Card.Config.ColorType][EnemyPokemon.Card.Config.ColorType];
        }
        
        if (bonus1 == 0) {
            Bonus1Text.color = Color.gray;
            Bonus1Text.text = "0";
        } else {
            Bonus1Text.color = Color.green;
            Bonus1Text.text = $"x{bonus1}";
        }
        
        if (bonus2 == 0) {
            Bonus2Text.color = Color.gray;
            Bonus2Text.text = "0";
        } else {
            Bonus2Text.color = Color.green;
            Bonus2Text.text = $"x{bonus2}";
        }
    }

    public void SwapPlayerPokemon(Pokemon newPokemon) {
        switch (State) {
            case FightState.WaitingForPlayerToSpawnHisFirstPokemon:
                PlayerPokemon = newPokemon;
                State = FightState.PlayerTurn;
                break;
            case FightState.PlayerTurn:
                PlayerHand.ReturnCard(PlayerPokemon.Card);
                Destroy(PlayerPokemon.gameObject);
                PlayerPokemon = newPokemon;
                break;
            case FightState.EnemyTurn:
                Debug.LogWarning("–ù–µ–ª—å–∑—è –∏–≥—Ä–∞—Ç—å –∫–∞—Ä—Ç—ã –≤–æ –≤—Ä–µ–º—è —Ö–æ–¥–∞ –ø—Ä–æ—Ç–∏–≤–Ω–∏–∫–∞");
                break;
            default:
                Debug.LogError("–ß—Ç–æ –∑–∞ —Å—Ç–µ–π—Ç?");
                break;
        }
    }

    private void OnPlayerCardPlayed(Card card) {
        if (card.Config.Type.IsSpell()) {
            switch (card.Config.Type) {
                case CardType.Hellfire:
                    EnemyPokemon.TakeDamage(5, card);
                    break;
                case CardType.Snow:
                    EnemyPokemon.AddEffect(EffectType.Snow, 2);
                    break;
                case CardType.Depression:
                    EnemyPokemon.AddEffect(EffectType.Depression, 1);
                    break;
                case CardType.Radioactive:
                    EnemyPokemon.AddEffect(EffectType.Poisoned, 3);
                    break;
                case CardType.PurpleHeart:
                    Debug.Log("Hi");
                    PlayerPokemon.Card.CurrentHealth.Restore();
                    PlayerPokemon.HealthView.Show(PlayerPokemon.Card.CurrentHealth);
                    break;
                default:
                    Debug.LogError($"–•—Ä–µ–Ω—å {card.Config.Type}");
                    break;
            }
        } else {
            Pokemon pokemon = Instantiate(card.Config.Pokemon, FightArea.transform);
            pokemon.Construct(card);
            pokemon.transform.position = PlayerPokemonSpawnPoint.position;
            SwapPlayerPokemon(pokemon);
        }
    }
    
    public void PlayerPressedTheAttackButton() {
        EnemyPokemon.ReadyToAttack += OnEnemyReadyToAttack;
        PlayerPokemon.Attack(EnemyPokemon);
        PlayerHand.Refill();
        SwitchTurnToEnemy();
    }
    
    public void SwitchTurnToPlayer() {
        if (EnemyPokemon != null) {
            EnemyPokemon.EndTurn();
        }

        foreach (var card in PlayerHand.Hand.Hand) {
            if (card.Config.Type == CardType.LovestruckToad) {
                card.CurrentHealth.Value = Math.Min(card.CurrentHealth.Value + (int)1.6, card.CurrentHealth.MaxAmount);
            }
        }
        
        if (PlayerPokemon != null) {
            PlayerPokemon.BeginTurn();
        }
        
        if (PlayerPokemon.Card.CurrentHealth.IsZero) {
            State = FightState.WaitingForPlayerToSpawnHisFirstPokemon;
        } else {
            State = FightState.PlayerTurn;
        }
    }
    
    public void OnEnemyReadyToAttack(Pokemon enemy) {
        EnemyPokemon.ReadyToAttack -= OnEnemyReadyToAttack;
        DoEnemyTurn();
        SwitchTurnToPlayer();
    }
    
    private void DoEnemyTurn() {
        if (EnemyPokemon != null && EnemyPokemon.HasEffect(EffectType.Depression)) {
            SwitchTurnToPlayer();
            return;
        }
        
        EnemyTurn turn = Enemy.DoTurn(EnemyPokemon, PlayerPokemon);
        switch (turn.Type) {
            case EnemyTurnType.Attack:
                EnemyPokemon.Attack(PlayerPokemon);
                break;
            case EnemyTurnType.PlayCard:
                Card card = turn.Card;
                if (!card.Config.Type.IsSpell()) {
                    Debug.LogError("–ù–µ —É–º–µ—é –∏–≥—Ä–∞—Ç—å —á—Ç–æ-—Ç–æ –∫—Ä–æ–º–µ —Å–ø–µ–ª–ª–æ–≤");
                    return;
                }
                Debug.Log($"–ò–≥—Ä–∞—é —Å–ø–µ–ª–ª {card} (–Ω–µ—Ç)");
                break;
            case EnemyTurnType.GiveUp:
                Debug.Log("–í—Ä–∞–≥ —Å–¥–∞–ª—Å—è");
                break;
            default:
                Debug.LogError($"–ù–µ —É–º–µ—é –æ–±—Ä–∞–±–∞—Ç—ã–≤–∞—Ç—å —Ö–æ–¥ {turn.Type}!");
                break;
        }
    }
    
    public void SwitchTurnToEnemy() {
        if (PlayerPokemon != null) {
            PlayerPokemon.EndTurn();
        }
        if (EnemyPokemon != null) {
            EnemyPokemon.BeginTurn();
        }
        
        State = FightState.EnemyTurn;
    }
}
